name: HTML CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install htmlhint
      run: npm install -g htmlhint

    - name: Run htmlhint on all HTML files
      run: htmlhint "**/*.html"
